[project]
name = "choicedesign"
version = "1.0.1"
description = "Experimental designs for discrete choice models."
authors = [
    {name = "ighdez",email = "joseignaciohernandezh@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "pandas (>=2.0.0,<4.0.0)",
    "openpyxl (>=3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.1.0,<8.0.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "sphinx (>=9.1.0,<10.0.0)",
    "sphinx-rtd-theme (>=3.1.0,<4.0.0)",
    "nbsphinx (>=0.9.8,<0.10.0)"
]
